#!/usr/bin/python3
import os
import sys
pwd = os.getcwd()
print("pmft v0.1")
if (sys.argv[1] == "help"):
    print("Usage: pmft [hex file path] [port]")
    sys.exit()
filepath = sys.argv[1]
if (sys.argv[2]):
    port = sys.argv[2]
    if (filepath[1] == "/"):
        os.system("python /usr/bin/avrdude-pmft/pmft-flasher.py -p atmega32u4 -c avr109 -C /usr/bin/avrdude-pmft/avrdude-pmft.conf -P " + port + " -U flash:w:" + filepath + ":i")
    else:
        os.system("python /usr/bin/avrdude-pmft/pmft-flasher.py -p atmega32u4 -c avr109 -C /usr/bin/avrdude-pmft/avrdude-pmft.conf -P " + port + " -U flash:w:" + pwd + "/" + filepath + ":i")
else:
    if (filepath[1] == "/"):
        os.system("python /usr/bin/avrdude-pmft/pmft-flasher.py -p atmega32u4 -c avr109 -C /usr/bin/avrdude-pmft/avrdude-pmft.conf -U flash:w:" + filepath + ":i")
    else:
        os.system("python /usr/bin/avrdude-pmft/pmft-flasher.py -p atmega32u4 -c avr109 -C /usr/bin/avrdude-pmft/avrdude-pmft.conf -U flash:w:" + pwd + "/" + filepath + ":i")
